version: '3'

services:

  backend:
    image: kedar1401/dockermern:backend
    container_name: backend
    ports:
      - 5000:5000  
    depends_on:
      - mongo
    environment:
      MONGOURI: mongodb+srv://kedardhule14:iCBSiQXdJ7VsRgSR@dockermern-clustor1.b62rpfw.mongodb.net/?retryWrites=true&w=majority&appName=DockerMERN-clustor1
      ACCESS_TOKEN_SECRET: DockerMERN
    networks:
      - app_network  # Join the network

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - 27017:27017
    networks:
      - app_network

  frontend:
    image: kedar1401/dockermern:frontend
    container_name: frontend
    depends_on:
      - backend
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  data-volume:
    driver: local